# AWS Production Deployment Infrastructure
# Comprehensive production infrastructure for Multimodal Librarian
# Generated through fresh execution of aws-production-deployment spec

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.1"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.2"
    }
  }

  # For production deployment:
  # 1. Run ./bootstrap-terraform-state.sh to create S3 bucket and DynamoDB table
  # 2. Run terraform init -backend-config=backend.conf
  # 
  # For development/testing, comment out the backend block below to use local state
  # backend "s3" {
  #   # Configuration will be provided via backend.conf file
  #   # Generated by bootstrap-terraform-state.sh script
  # }
}

# Primary AWS Provider
provider "aws" {
  region = var.aws_region

  default_tags {
    tags = local.common_tags
  }
}

# Secondary AWS Provider for cross-region backup
provider "aws" {
  alias  = "backup_region"
  region = var.backup_region

  default_tags {
    tags = local.common_tags
  }
}

# Local values for common configurations
locals {
  common_tags = {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
    CostCenter  = var.cost_center
    Owner       = var.owner
    CreatedBy   = "aws-production-deployment-spec"
  }

  name_prefix = "${var.project_name}-${var.environment}"
}

# Random password for database credentials
resource "random_password" "neptune_password" {
  length  = 32
  special = true
}

resource "random_password" "opensearch_password" {
  length  = 32
  special = true
}

# VPC Module - Multi-AZ networking infrastructure
module "vpc" {
  source = "./modules/vpc"

  name_prefix            = local.name_prefix
  vpc_cidr               = var.vpc_cidr
  availability_zones     = var.availability_zones
  public_subnet_cidrs    = var.public_subnet_cidrs
  private_subnet_cidrs   = var.private_subnet_cidrs
  single_nat_gateway     = var.single_nat_gateway
  shared_nat_gateway_id  = var.shared_nat_gateway_id
  log_retention_days     = var.log_retention_days

  tags = local.common_tags
}
# Security Module - Security groups, IAM roles, and encryption
module "security" {
  source = "./modules/security"

  name_prefix         = local.name_prefix
  vpc_id              = module.vpc.vpc_id
  container_port      = var.container_port
  enable_key_rotation = var.kms_key_rotation

  # Security Controls Configuration
  enable_waf          = var.enable_waf
  enable_guardduty    = var.enable_guardduty
  enable_security_hub = var.enable_security_hub
  enable_inspector    = var.enable_inspector
  enable_config       = var.enable_config
  waf_rate_limit      = var.waf_rate_limit
  log_retention_days  = var.log_retention_days

  tags = local.common_tags
}
# SSL Certificate (conditional based on domain name)
resource "aws_acm_certificate" "main" {
  count = var.domain_name != "" ? 1 : 0

  domain_name       = var.domain_name
  validation_method = "DNS"

  subject_alternative_names = [
    "*.${var.domain_name}"
  ]

  lifecycle {
    create_before_destroy = true
  }

  tags = merge(local.common_tags, {
    Name = "${local.name_prefix}-ssl-certificate"
  })
}

# CloudTrail for audit logging
resource "aws_cloudtrail" "main" {
  count = var.enable_cloudtrail ? 1 : 0

  name           = "${local.name_prefix}-cloudtrail"
  s3_bucket_name = aws_s3_bucket.cloudtrail[0].bucket

  event_selector {
    read_write_type                  = "All"
    include_management_events        = true
    exclude_management_event_sources = []

    data_resource {
      type   = "AWS::S3::Object"
      values = ["arn:aws:s3"]
    }
  }

  depends_on = [aws_s3_bucket_policy.cloudtrail[0]]

  tags = local.common_tags
}

# S3 Bucket for CloudTrail logs
resource "aws_s3_bucket" "cloudtrail" {
  count = var.enable_cloudtrail ? 1 : 0

  bucket        = "${local.name_prefix}-cloudtrail-logs-${random_id.bucket_suffix.hex}"
  force_destroy = true

  tags = merge(local.common_tags, {
    Name = "${local.name_prefix}-cloudtrail-logs"
  })
}

# Random ID for bucket suffix
resource "random_id" "bucket_suffix" {
  byte_length = 4
}

# S3 Bucket versioning for CloudTrail
resource "aws_s3_bucket_versioning" "cloudtrail" {
  count = var.enable_cloudtrail ? 1 : 0

  bucket = aws_s3_bucket.cloudtrail[0].id
  versioning_configuration {
    status = "Enabled"
  }
}

# S3 Bucket encryption for CloudTrail
resource "aws_s3_bucket_server_side_encryption_configuration" "cloudtrail" {
  count = var.enable_cloudtrail ? 1 : 0

  bucket = aws_s3_bucket.cloudtrail[0].id

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = module.security.kms_key_arn
      sse_algorithm     = "aws:kms"
    }
  }
}

# S3 Bucket policy for CloudTrail
resource "aws_s3_bucket_policy" "cloudtrail" {
  count = var.enable_cloudtrail ? 1 : 0

  bucket = aws_s3_bucket.cloudtrail[0].id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "AWSCloudTrailAclCheck"
        Effect = "Allow"
        Principal = {
          Service = "cloudtrail.amazonaws.com"
        }
        Action   = "s3:GetBucketAcl"
        Resource = aws_s3_bucket.cloudtrail[0].arn
      },
      {
        Sid    = "AWSCloudTrailWrite"
        Effect = "Allow"
        Principal = {
          Service = "cloudtrail.amazonaws.com"
        }
        Action   = "s3:PutObject"
        Resource = "${aws_s3_bucket.cloudtrail[0].arn}/*"
        Condition = {
          StringEquals = {
            "s3:x-amz-acl" = "bucket-owner-full-control"
          }
        }
      }
    ]
  })
}

# Secrets Manager secret for Neptune connection
resource "aws_secretsmanager_secret" "neptune" {
  name        = "${local.name_prefix}/neptune/connection"
  description = "Neptune database connection information"

  kms_key_id = module.security.kms_key_arn

  tags = merge(local.common_tags, {
    Name = "${local.name_prefix}-neptune-secret"
  })
}

# Secrets Manager secret for OpenSearch connection
resource "aws_secretsmanager_secret" "opensearch" {
  name        = "${local.name_prefix}/opensearch/connection"
  description = "OpenSearch domain connection information"

  kms_key_id = module.security.kms_key_arn

  tags = merge(local.common_tags, {
    Name = "${local.name_prefix}-opensearch-secret"
  })
}

# Secrets Manager secret for API keys
resource "aws_secretsmanager_secret" "api_keys" {
  name        = "${local.name_prefix}/api-keys"
  description = "API keys for external services"

  kms_key_id = module.security.kms_key_arn

  tags = merge(local.common_tags, {
    Name = "${local.name_prefix}-api-keys-secret"
  })
}

# API keys secret version (placeholder values)
resource "aws_secretsmanager_secret_version" "api_keys" {
  secret_id = aws_secretsmanager_secret.api_keys.id

  secret_string = jsonencode({
    openai_api_key = "placeholder-openai-key"
    google_api_key = "placeholder-google-key"
    gemini_api_key = "placeholder-gemini-key"
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}
# Databases Module - Neptune and OpenSearch with production configuration
module "databases" {
  source = "./modules/databases"

  name_prefix        = local.name_prefix
  private_subnet_ids = module.vpc.private_subnet_ids
  availability_zones = var.availability_zones
  security_group_ids = [module.security.neptune_security_group_id, module.security.opensearch_security_group_id]
  kms_key_arn        = module.security.kms_key_arn
  random_suffix      = random_id.bucket_suffix.hex

  # Neptune Configuration
  neptune_instance_type   = var.neptune_instance_type
  neptune_instance_count  = var.neptune_instance_count
  backup_retention_period = var.neptune_backup_retention
  neptune_backup_window   = var.neptune_backup_window

  # OpenSearch Configuration
  opensearch_instance_type   = var.opensearch_instance_type
  opensearch_instance_count  = var.opensearch_instance_count
  opensearch_master_password = random_password.opensearch_password.result

  # Logging Configuration
  log_retention_days = var.log_retention_days

  tags = local.common_tags
}

# Update Neptune secret with actual connection information
resource "aws_secretsmanager_secret_version" "neptune" {
  secret_id = aws_secretsmanager_secret.neptune.id

  secret_string = jsonencode({
    endpoint        = module.databases.neptune_endpoint
    reader_endpoint = module.databases.neptune_reader_endpoint
    port            = module.databases.neptune_port
    cluster_id      = module.databases.neptune_cluster_id
    engine          = "neptune"
    ssl_enabled     = true
  })
}

# Update OpenSearch secret with actual connection information
resource "aws_secretsmanager_secret_version" "opensearch" {
  secret_id = aws_secretsmanager_secret.opensearch.id

  secret_string = jsonencode({
    endpoint        = "https://${module.databases.opensearch_endpoint}"
    kibana_endpoint = "https://${module.databases.opensearch_kibana_endpoint}"
    domain_name     = module.databases.opensearch_domain_name
    master_user     = "admin"
    master_password = random_password.opensearch_password.result
    ssl_enabled     = true
  })
}
# Random password for Redis auth token
resource "random_password" "redis_auth_token" {
  length  = 32
  special = true
}

# Storage Module - EFS for Model Cache
module "storage" {
  source = "./modules/storage"

  name_prefix        = local.name_prefix
  environment        = var.environment
  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_subnet_ids

  # Security
  efs_security_group_id = module.security.efs_security_group_id
  kms_key_arn           = module.security.kms_key_arn

  # Logging
  log_retention_days = var.log_retention_days

  tags = local.common_tags
}

# Application Module - ECS Fargate, ALB, CloudFront, and ElastiCache
module "application" {
  source = "./modules/application"

  name_prefix        = local.name_prefix
  vpc_id             = module.vpc.vpc_id
  public_subnet_ids  = module.vpc.public_subnet_ids
  private_subnet_ids = module.vpc.private_subnet_ids

  # Security Groups
  alb_security_group_id         = module.security.alb_security_group_id
  ecs_security_group_id         = module.security.ecs_security_group_id
  elasticache_security_group_id = module.security.elasticache_security_group_id

  # IAM Roles
  ecs_task_execution_role_arn = module.security.ecs_task_execution_role_arn
  ecs_task_role_arn           = module.security.ecs_task_role_arn

  # Encryption
  kms_key_arn   = module.security.kms_key_arn
  random_suffix = random_id.bucket_suffix.hex

  # Application Configuration
  aws_region       = var.aws_region
  environment      = var.environment
  container_port   = var.container_port
  health_check_path = var.health_check_path
  ecs_cpu          = var.ecs_cpu
  ecs_memory       = var.ecs_memory
  min_capacity     = var.min_capacity
  max_capacity     = var.max_capacity

  # ECR Configuration
  ecr_repository_url = var.ecr_repository_url

  # Secrets
  neptune_secret_arn    = aws_secretsmanager_secret.neptune.arn
  opensearch_secret_arn = aws_secretsmanager_secret.opensearch.arn
  redis_auth_token      = random_password.redis_auth_token.result

  # SSL Configuration
  certificate_arn = var.certificate_arn

  # Logging
  log_retention_days = var.log_retention_days

  # EFS Configuration
  efs_file_system_id   = module.storage.efs_file_system_id
  efs_access_point_id  = module.storage.efs_access_point_id

  tags = local.common_tags
}

# WAF Association with Application Load Balancer
resource "aws_wafv2_web_acl_association" "main" {
  count = var.enable_waf ? 1 : 0

  resource_arn = module.application.load_balancer_arn
  web_acl_arn  = module.security.waf_web_acl_arn

  depends_on = [module.application, module.security]
}

# Monitoring Module - CloudWatch logging, metrics, dashboards, and alerting
module "monitoring" {
  source = "./modules/monitoring"

  name_prefix = local.name_prefix
  environment = var.environment
  aws_region  = var.aws_region
  kms_key_arn = module.security.kms_key_arn

  # Monitoring Configuration
  log_retention_days = var.log_retention_days

  # ECS Monitoring
  ecs_service_name = module.application.ecs_service_name
  ecs_cluster_name = module.application.ecs_cluster_name

  # ALB Monitoring
  alb_arn_suffix = module.application.alb_arn_suffix

  # Database Monitoring
  neptune_cluster_id     = module.databases.neptune_cluster_id
  opensearch_domain_name = module.databases.opensearch_domain_name

  # Security Monitoring
  waf_web_acl_arn             = module.security.waf_web_acl_arn
  enable_waf_monitoring       = var.enable_waf
  enable_guardduty_monitoring = var.enable_guardduty

  # Container Failure Monitor
  enable_container_failure_monitor = var.enable_container_failure_monitor
  alert_email                      = var.alert_email

  tags = local.common_tags
}

# Backup Module - Backup and recovery infrastructure
module "backup" {
  source = "./modules/backup"

  providers = {
    aws.backup_region = aws.backup_region
  }

  name_prefix   = local.name_prefix
  project_name  = var.project_name
  environment   = var.environment
  aws_region    = var.aws_region
  kms_key_arn   = module.security.kms_key_arn
  random_suffix = random_id.bucket_suffix.hex

  # Backup Configuration
  backup_retention_days             = var.backup_retention_days
  enable_cross_region_backup        = var.enable_cross_region_backup
  backup_region                     = var.backup_region
  opensearch_snapshot_hour          = var.opensearch_snapshot_hour
  backup_monitoring_enabled         = var.backup_monitoring_enabled
  disaster_recovery_testing_enabled = var.disaster_recovery_testing_enabled

  # Logging Configuration
  log_retention_days = var.log_retention_days

  # SNS Topic for alerts (if notification email is provided)
  sns_topic_arn = var.notification_email != "" ? aws_sns_topic.notifications[0].arn : ""

  tags = local.common_tags
}

# SNS Topic for notifications (conditional)
resource "aws_sns_topic" "notifications" {
  count = var.notification_email != "" ? 1 : 0

  name         = "${local.name_prefix}-notifications"
  display_name = "Backup and Monitoring Notifications"
  kms_master_key_id = module.security.kms_key_arn

  tags = local.common_tags
}

# SNS Topic Subscription for email notifications
resource "aws_sns_topic_subscription" "email_notifications" {
  count = var.notification_email != "" ? 1 : 0

  topic_arn = aws_sns_topic.notifications[0].arn
  protocol  = "email"
  endpoint  = var.notification_email
}

# Cost Optimization Module - Budget monitoring, right-sizing, and resource cleanup
module "cost_optimization" {
  source = "./modules/cost_optimization"

  name_prefix   = local.name_prefix
  project_name  = var.project_name
  environment   = var.environment

  # ECS Configuration for monitoring
  ecs_cluster_name = module.application.ecs_cluster_name
  ecs_service_name = module.application.ecs_service_name

  # Budget Configuration
  monthly_budget_limit        = var.monthly_budget_limit
  ecs_budget_limit           = var.ecs_budget_limit
  database_budget_limit      = var.database_budget_limit
  budget_notification_emails = var.budget_alert_emails

  # Cost Optimization Features
  enable_detailed_budgets        = var.enable_cost_optimization
  enable_cost_anomaly_detection  = var.enable_cost_optimization
  enable_cost_alerts            = var.enable_cost_optimization
  enable_right_sizing_alerts    = var.enable_cost_optimization
  enable_reserved_instances     = var.enable_reserved_instances
  enable_resource_cleanup       = false # Disabled by default for safety
  enable_s3_lifecycle_optimization = false # Disabled by default

  # Thresholds and Targets
  cost_alert_threshold              = var.cost_anomaly_threshold * 3 # Set higher than anomaly threshold
  cost_anomaly_threshold           = var.cost_anomaly_threshold
  cpu_underutilization_threshold   = 20  # 20% CPU utilization threshold
  memory_underutilization_threshold = 30  # 30% memory utilization threshold
  target_cpu_utilization          = 70  # Target 70% CPU for auto-scaling
  target_memory_utilization       = 80  # Target 80% memory for auto-scaling

  # SNS Topic for alerts (if notification email is provided)
  sns_topic_arn = var.notification_email != "" ? aws_sns_topic.notifications[0].arn : ""

  tags = local.common_tags
}