"""
Tests for KGQAStrategy.

Covers the core generate() flow, question/answer generation helpers,
short-chunk filtering, and graceful error handling for Neo4j and
Milvus failures.

# Feature: medical-knowledge-finetuning
# Property 2: KG question generation includes concept name
# Property 3: KG answer preserves source attribution

Validates: Requirements 1.3, 1.4
"""

from unittest.mock import AsyncMock, MagicMock

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from multimodal_librarian.ml.kg_qa_strategy import (
    KGQAStrategy,
    _count_tokens,
    _generate_answer,
    _generate_question,
)
from multimodal_librarian.ml.models import InstructionTuningPair
from multimodal_librarian.ml.rag_qa_strategy import (
    DEFAULT_QUESTION_TEMPLATES,
    TEMPLATES_BY_SEMANTIC_TYPE,
)

# ---------------------------------------------------------------
# Hypothesis strategies for Property 2
# ---------------------------------------------------------------

# All known semantic types from TEMPLATES_BY_SEMANTIC_TYPE,
# plus arbitrary strings to exercise the default fallback path.
_KNOWN_SEMANTIC_TYPES = list(TEMPLATES_BY_SEMANTIC_TYPE.keys())

# Maximum template index across all template lists (used to cycle templates).
_MAX_TEMPLATE_INDEX = max(
    len(ts) for ts in (
        list(TEMPLATES_BY_SEMANTIC_TYPE.values())
        + [DEFAULT_QUESTION_TEMPLATES]
    )
)


def _concept_name() -> st.SearchStrategy[str]:
    """Non-empty concept name with at least one non-whitespace char."""
    return st.text(
        alphabet=st.characters(
            whitelist_categories=("L", "N", "Zs", "Pd"),
            whitelist_characters="-' ",
        ),
        min_size=1,
        max_size=200,
    ).filter(lambda s: s.strip())


def _semantic_type() -> st.SearchStrategy[str]:
    """Known semantic type or arbitrary string (fallback path)."""
    return st.one_of(
        st.sampled_from(_KNOWN_SEMANTIC_TYPES),
        st.text(min_size=1, max_size=100).filter(
            lambda s: s.strip()
        ),
    )


def _synonyms() -> st.SearchStrategy[list[str] | None]:
    """Optional list of synonym strings."""
    return st.one_of(
        st.none(),
        st.lists(
            st.text(min_size=1, max_size=100).filter(
                lambda s: s.strip()
            ),
            max_size=10,
        ),
    )


def _template_index() -> st.SearchStrategy[int]:
    """Non-negative template index (may exceed list length)."""
    return st.integers(
        min_value=0, max_value=_MAX_TEMPLATE_INDEX * 3
    )


# ---------------------------------------------------------------
# Property 2: KG question generation includes concept name
# ---------------------------------------------------------------


@pytest.mark.pbt
@pytest.mark.unit
class TestKGQuestionGenerationIncludesConceptName:
    """Property 2: KG question generation includes concept name.

    For any Concept with a non-empty name, semantic type, and optional
    synonyms, the question generated by _generate_question SHALL contain
    the concept name (case-insensitive match).

    Validates: Requirements 1.3
    """

    @given(
        concept_name=_concept_name(),
        semantic_type=_semantic_type(),
        synonyms=_synonyms(),
        template_index=_template_index(),
    )
    @settings(max_examples=200)
    def test_question_contains_concept_name_case_insensitive(
        self,
        concept_name: str,
        semantic_type: str,
        synonyms: list[str] | None,
        template_index: int,
    ) -> None:
        """The generated question always contains the concept name
        (case-insensitive)."""
        question = _generate_question(
            concept_name=concept_name,
            semantic_type=semantic_type,
            synonyms=synonyms,
            template_index=template_index,
        )
        assert concept_name.lower() in question.lower(), (
            f"Concept name {concept_name!r} not found "
            f"in question: {question!r}"
        )

    @given(
        concept_name=_concept_name(),
        semantic_type=st.sampled_from(_KNOWN_SEMANTIC_TYPES),
        template_index=_template_index(),
    )
    @settings(max_examples=200)
    def test_question_contains_concept_name_known_types(
        self,
        concept_name: str,
        semantic_type: str,
        template_index: int,
    ) -> None:
        """For known semantic types, the question contains the concept name."""
        question = _generate_question(
            concept_name=concept_name,
            semantic_type=semantic_type,
            template_index=template_index,
        )
        assert concept_name.lower() in question.lower(), (
            f"Concept name {concept_name!r} not found in question "
            f"(type={semantic_type!r}): {question!r}"
        )

    @given(
        concept_name=_concept_name(),
        semantic_type=st.text(min_size=1, max_size=100).filter(
            lambda s: s.strip() and s not in _KNOWN_SEMANTIC_TYPES
        ),
        template_index=_template_index(),
    )
    @settings(max_examples=200)
    def test_question_contains_concept_name_fallback_templates(
        self,
        concept_name: str,
        semantic_type: str,
        template_index: int,
    ) -> None:
        """For unknown semantic types (fallback templates), the question
        still contains the concept name."""
        question = _generate_question(
            concept_name=concept_name,
            semantic_type=semantic_type,
            template_index=template_index,
        )
        assert concept_name.lower() in question.lower(), (
            f"Concept name {concept_name!r} not found in fallback question: "
            f"{question!r}"
        )

    @given(concept_name=_concept_name())
    @settings(max_examples=100)
    def test_question_is_non_empty_string(
        self,
        concept_name: str,
    ) -> None:
        """The generated question is always a non-empty string."""
        question = _generate_question(
            concept_name=concept_name,
            semantic_type="Disease or Syndrome",
        )
        assert isinstance(question, str)
        assert len(question.strip()) > 0


# ---------------------------------------------------------------
# Hypothesis strategies for Property 3
# ---------------------------------------------------------------


def _source_document() -> st.SearchStrategy[str]:
    """Non-empty source document title."""
    return st.text(
        alphabet=st.characters(
            whitelist_categories=("L", "N", "Zs"),
            whitelist_characters="'-.,:()",
        ),
        min_size=1,
        max_size=200,
    ).filter(lambda s: s.strip())


def _chunk_id() -> st.SearchStrategy[str]:
    """Non-empty chunk identifier."""
    return st.from_regex(r"[a-zA-Z0-9][a-zA-Z0-9_-]{0,49}", fullmatch=True)


def _chunk_content() -> st.SearchStrategy[str]:
    """Non-empty chunk content with at least a few words."""
    # Build content from word lists to avoid heavy filtering
    return st.lists(
        st.text(
            alphabet=st.characters(whitelist_categories=("L", "N")),
            min_size=1,
            max_size=20,
        ).filter(lambda s: s.strip()),
        min_size=3,
        max_size=50,
    ).map(lambda words: " ".join(words))


# ---------------------------------------------------------------
# Property 3: KG answer preserves source attribution
# ---------------------------------------------------------------


@pytest.mark.pbt
@pytest.mark.unit
class TestKGAnswerPreservesSourceAttribution:
    """Property 3: KG answer preserves source attribution.

    For any Concept-Chunk pair where the chunk has a source document
    title and chunk ID, the answer generated by KG_QA_Strategy SHALL
    include both the source document title and the chunk ID in the
    output.

    Validates: Requirements 1.4
    """

    @given(
        concept_name=_concept_name(),
        semantic_type=_semantic_type(),
        chunk_content=_chunk_content(),
        source_document=_source_document(),
        chunk_id=_chunk_id(),
        synonyms=_synonyms(),
    )
    @settings(max_examples=200)
    def test_answer_contains_source_document_title(
        self,
        concept_name: str,
        semantic_type: str,
        chunk_content: str,
        source_document: str,
        chunk_id: str,
        synonyms: list[str] | None,
    ) -> None:
        """The generated answer always contains the source document title."""
        answer = _generate_answer(
            concept_name=concept_name,
            semantic_type=semantic_type,
            chunk_content=chunk_content,
            source_document=source_document,
            chunk_id=chunk_id,
            synonyms=synonyms,
        )
        assert source_document in answer, (
            f"Source document {source_document!r} not found "
            f"in answer: {answer!r}"
        )

    @given(
        concept_name=_concept_name(),
        semantic_type=_semantic_type(),
        chunk_content=_chunk_content(),
        source_document=_source_document(),
        chunk_id=_chunk_id(),
        synonyms=_synonyms(),
    )
    @settings(max_examples=200)
    def test_answer_contains_chunk_id(
        self,
        concept_name: str,
        semantic_type: str,
        chunk_content: str,
        source_document: str,
        chunk_id: str,
        synonyms: list[str] | None,
    ) -> None:
        """The generated answer always contains the chunk ID."""
        answer = _generate_answer(
            concept_name=concept_name,
            semantic_type=semantic_type,
            chunk_content=chunk_content,
            source_document=source_document,
            chunk_id=chunk_id,
            synonyms=synonyms,
        )
        assert chunk_id in answer, (
            f"Chunk ID {chunk_id!r} not found "
            f"in answer: {answer!r}"
        )

    @given(
        concept_name=_concept_name(),
        semantic_type=_semantic_type(),
        chunk_content=_chunk_content(),
        source_document=_source_document(),
        chunk_id=_chunk_id(),
        synonyms=_synonyms(),
    )
    @settings(max_examples=200)
    def test_answer_contains_both_attribution_fields(
        self,
        concept_name: str,
        semantic_type: str,
        chunk_content: str,
        source_document: str,
        chunk_id: str,
        synonyms: list[str] | None,
    ) -> None:
        """The generated answer contains both source document and chunk ID
        together in a source attribution block."""
        answer = _generate_answer(
            concept_name=concept_name,
            semantic_type=semantic_type,
            chunk_content=chunk_content,
            source_document=source_document,
            chunk_id=chunk_id,
            synonyms=synonyms,
        )
        assert source_document in answer and chunk_id in answer, (
            f"Source attribution incomplete in answer. "
            f"Expected doc={source_document!r} and id={chunk_id!r} "
            f"in: {answer!r}"
        )

    @given(
        concept_name=_concept_name(),
        semantic_type=_semantic_type(),
        chunk_content=_chunk_content(),
        source_document=_source_document(),
        chunk_id=_chunk_id(),
    )
    @settings(max_examples=200)
    def test_answer_contains_chunk_content(
        self,
        concept_name: str,
        semantic_type: str,
        chunk_content: str,
        source_document: str,
        chunk_id: str,
    ) -> None:
        """The generated answer preserves the original chunk content."""
        answer = _generate_answer(
            concept_name=concept_name,
            semantic_type=semantic_type,
            chunk_content=chunk_content,
            source_document=source_document,
            chunk_id=chunk_id,
        )
        assert chunk_content.strip() in answer, (
            f"Chunk content not preserved in answer. "
            f"Expected {chunk_content.strip()!r} in: {answer!r}"
        )


# ---------------------------------------------------------------
# Hypothesis strategies for Property 4
# ---------------------------------------------------------------


def _short_chunk_content(max_tokens: int = 49) -> st.SearchStrategy[str]:
    """Chunk content with fewer than max_tokens whitespace-separated words."""
    return st.lists(
        st.text(
            alphabet=st.characters(whitelist_categories=("L", "N")),
            min_size=1,
            max_size=20,
        ).filter(lambda s: s.strip()),
        min_size=0,
        max_size=max_tokens - 1,
    ).map(lambda words: " ".join(words))


def _long_chunk_content(min_tokens: int = 50) -> st.SearchStrategy[str]:
    """Chunk content with at least min_tokens whitespace-separated words."""
    return st.lists(
        st.text(
            alphabet=st.characters(whitelist_categories=("L", "N")),
            min_size=1,
            max_size=20,
        ).filter(lambda s: s.strip()),
        min_size=min_tokens,
        max_size=min_tokens + 100,
    ).map(lambda words: " ".join(words))


def _min_chunk_tokens_threshold() -> st.SearchStrategy[int]:
    """Configurable minimum chunk token threshold."""
    return st.integers(min_value=1, max_value=200)


# ---------------------------------------------------------------
# Property 4: Short chunk filtering
# ---------------------------------------------------------------


@pytest.mark.pbt
@pytest.mark.unit
class TestShortChunkFiltering:
    """Property 4: Short chunk filtering.

    For any chunk with fewer than min_chunk_tokens tokens of content,
    the KG_QA_Strategy SHALL skip that Concept-Chunk pair. For any
    chunk with min_chunk_tokens or more tokens, the pair SHALL be
    processed (not skipped due to length).

    # Feature: medical-knowledge-finetuning, Property 4: Short chunk filtering

    Validates: Requirements 1.5
    """

    @given(
        content=_short_chunk_content(max_tokens=50),
    )
    @settings(max_examples=200)
    def test_chunks_below_50_tokens_are_skipped(
        self,
        content: str,
    ) -> None:
        """Chunks with < 50 tokens are always below the default threshold."""
        token_count = _count_tokens(content)
        assert token_count < 50, (
            f"Expected < 50 tokens but got {token_count} "
            f"for content: {content!r}"
        )

    @given(
        content=_long_chunk_content(min_tokens=50),
    )
    @settings(max_examples=200)
    def test_chunks_at_or_above_50_tokens_are_processed(
        self,
        content: str,
    ) -> None:
        """Chunks with >= 50 tokens meet the default threshold."""
        token_count = _count_tokens(content)
        assert token_count >= 50, (
            f"Expected >= 50 tokens but got {token_count} "
            f"for content: {content!r}"
        )

    @given(
        threshold=_min_chunk_tokens_threshold(),
        data=st.data(),
    )
    @settings(max_examples=200)
    def test_short_chunks_skipped_at_any_threshold(
        self,
        threshold: int,
        data: st.DataObject,
    ) -> None:
        """For any configurable threshold, chunks below it are skipped."""
        # Generate content with fewer tokens than the threshold
        short_words = data.draw(
            st.lists(
                st.text(
                    alphabet=st.characters(
                        whitelist_categories=("L", "N")
                    ),
                    min_size=1,
                    max_size=15,
                ).filter(lambda s: s.strip()),
                min_size=0,
                max_size=max(threshold - 1, 0),
            )
        )
        content = " ".join(short_words)
        token_count = _count_tokens(content)
        assert token_count < threshold, (
            f"Expected < {threshold} tokens but got {token_count}"
        )

    @given(
        threshold=_min_chunk_tokens_threshold(),
        data=st.data(),
    )
    @settings(max_examples=200)
    def test_long_chunks_processed_at_any_threshold(
        self,
        threshold: int,
        data: st.DataObject,
    ) -> None:
        """For any configurable threshold, chunks at or above it are
        processed."""
        long_words = data.draw(
            st.lists(
                st.text(
                    alphabet=st.characters(
                        whitelist_categories=("L", "N")
                    ),
                    min_size=1,
                    max_size=15,
                ).filter(lambda s: s.strip()),
                min_size=threshold,
                max_size=threshold + 50,
            )
        )
        content = " ".join(long_words)
        token_count = _count_tokens(content)
        assert token_count >= threshold, (
            f"Expected >= {threshold} tokens but got {token_count}"
        )

    @given(
        content=_short_chunk_content(max_tokens=50),
        concept_name=_concept_name(),
        semantic_type=_semantic_type(),
        source_document=_source_document(),
        chunk_id=_chunk_id(),
    )
    @settings(max_examples=100)
    @pytest.mark.asyncio
    async def test_generate_skips_short_chunks_end_to_end(
        self,
        content: str,
        concept_name: str,
        semantic_type: str,
        source_document: str,
        chunk_id: str,
    ) -> None:
        """End-to-end: generate() skips chunks with < 50 tokens."""
        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(
            return_value=[
                {
                    "name": concept_name,
                    "cui": "C0000001",
                    "semantic_type": semantic_type,
                    "synonyms": None,
                    "chunk_ids": [chunk_id],
                }
            ]
        )
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(
            return_value={
                "chunk_id": chunk_id,
                "content": content,
                "document_title": source_document,
                "metadata": {
                    "content": content,
                    "title": source_document,
                },
            }
        )
        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        pairs = await strategy.generate(
            target_count=5, min_chunk_tokens=50
        )
        assert len(pairs) == 0, (
            f"Expected 0 pairs for short chunk ({_count_tokens(content)} "
            f"tokens) but got {len(pairs)}"
        )

    @given(
        content=_long_chunk_content(min_tokens=50),
        concept_name=_concept_name(),
        semantic_type=_semantic_type(),
        source_document=_source_document(),
        chunk_id=_chunk_id(),
    )
    @settings(max_examples=100)
    @pytest.mark.asyncio
    async def test_generate_processes_long_chunks_end_to_end(
        self,
        content: str,
        concept_name: str,
        semantic_type: str,
        source_document: str,
        chunk_id: str,
    ) -> None:
        """End-to-end: generate() processes chunks with >= 50 tokens."""
        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(
            return_value=[
                {
                    "name": concept_name,
                    "cui": "C0000001",
                    "semantic_type": semantic_type,
                    "synonyms": None,
                    "chunk_ids": [chunk_id],
                }
            ]
        )
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(
            return_value={
                "chunk_id": chunk_id,
                "content": content,
                "document_title": source_document,
                "metadata": {
                    "content": content,
                    "title": source_document,
                },
            }
        )
        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        pairs = await strategy.generate(
            target_count=1, min_chunk_tokens=50
        )
        assert len(pairs) == 1, (
            f"Expected 1 pair for long chunk ({_count_tokens(content)} "
            f"tokens) but got {len(pairs)}"
        )
        assert isinstance(pairs[0], InstructionTuningPair)


# ---------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------


def _make_concept(
    name="Metformin",
    cui="C0025598",
    semantic_type="Pharmacologic Substance",
    synonyms=None,
    chunk_ids=None,
):
    """Build a concept dict matching the Neo4j query result shape."""
    return {
        "name": name,
        "cui": cui,
        "semantic_type": semantic_type,
        "synonyms": synonyms or ["Glucophage"],
        "chunk_ids": chunk_ids or ["chunk-001"],
    }


def _make_chunk(
    chunk_id="chunk-001",
    content=(
        "Metformin is a biguanide oral antidiabetic agent used as "
        "first-line therapy for type 2 diabetes mellitus. It works "
        "primarily by decreasing hepatic glucose production and "
        "improving insulin sensitivity in peripheral tissues. "
        "Metformin also reduces intestinal absorption of glucose "
        "and improves glucose uptake and utilization. Common side "
        "effects include gastrointestinal disturbances such as "
        "nausea, diarrhea, and abdominal discomfort. It is "
        "generally well tolerated and does not cause weight gain "
        "or hypoglycemia when used as monotherapy."
    ),
    document_title="Harrison's Principles of Internal Medicine",
):
    """Build a chunk dict matching the vector store return shape."""
    return {
        "chunk_id": chunk_id,
        "content": content,
        "document_title": document_title,
        "section": "Pharmacology",
        "source_id": "harrisons-v20",
        "metadata": {
            "content": content,
            "title": document_title,
        },
    }


@pytest.fixture
def mock_neo4j():
    """Mock Neo4j client with execute_query."""
    client = MagicMock()
    client.execute_query = AsyncMock(
        return_value=[_make_concept()]
    )
    return client


@pytest.fixture
def mock_vector():
    """Mock vector client with get_chunk_by_id."""
    client = MagicMock()
    client.get_chunk_by_id = AsyncMock(
        return_value=_make_chunk()
    )
    return client


@pytest.fixture
def strategy(mock_neo4j, mock_vector):
    return KGQAStrategy(
        neo4j_client=mock_neo4j,
        vector_client=mock_vector,
    )


# ---------------------------------------------------------------
# Helper function tests
# ---------------------------------------------------------------


class TestCountTokens:
    def test_empty_string(self):
        assert _count_tokens("") == 0

    def test_single_word(self):
        assert _count_tokens("hello") == 1

    def test_multiple_words(self):
        assert _count_tokens("one two three four") == 4


class TestGenerateQuestion:
    def test_contains_concept_name(self):
        """Property 2: question contains concept name."""
        q = _generate_question(
            "Metformin",
            "Pharmacologic Substance",
        )
        assert "Metformin" in q

    def test_uses_semantic_type_template(self):
        q = _generate_question(
            "Aspirin",
            "Pharmacologic Substance",
            template_index=0,
        )
        assert "Aspirin" in q
        # First template for Pharmacologic Substance from
        # TEMPLATES_BY_SEMANTIC_TYPE asks about mechanism of action
        assert "mechanism of action" in q.lower()

    def test_fallback_template_for_unknown_type(self):
        q = _generate_question(
            "SomeEntity",
            "Unknown Semantic Type",
        )
        assert "SomeEntity" in q
        # Falls back to DEFAULT_QUESTION_TEMPLATES
        assert "clinical significance" in q.lower()

    def test_template_cycling(self):
        """Different template_index values cycle templates."""
        q0 = _generate_question("X", "Disease or Syndrome", template_index=0)
        q1 = _generate_question("X", "Disease or Syndrome", template_index=1)
        assert q0 != q1
        assert "X" in q0
        assert "X" in q1


class TestGenerateAnswer:
    def test_contains_source_attribution(self):
        """Property 3: answer includes source doc and chunk ID."""
        answer = _generate_answer(
            concept_name="Metformin",
            semantic_type="Pharmacologic Substance",
            chunk_content="Metformin is a biguanide.",
            source_document="Harrison's",
            chunk_id="chunk-001",
        )
        assert "Harrison's" in answer
        assert "chunk-001" in answer

    def test_contains_chunk_content(self):
        answer = _generate_answer(
            concept_name="Metformin",
            semantic_type="Pharmacologic Substance",
            chunk_content="Metformin is a biguanide.",
            source_document="Harrison's",
            chunk_id="chunk-001",
        )
        assert "Metformin is a biguanide." in answer

    def test_includes_synonyms(self):
        answer = _generate_answer(
            concept_name="Metformin",
            semantic_type="Pharmacologic Substance",
            chunk_content="Content here.",
            source_document="Doc",
            chunk_id="c1",
            synonyms=["Glucophage", "Fortamet"],
        )
        assert "Glucophage" in answer
        assert "Fortamet" in answer

    def test_excludes_concept_name_from_synonyms(self):
        answer = _generate_answer(
            concept_name="Metformin",
            semantic_type="Pharmacologic Substance",
            chunk_content="Content here.",
            source_document="Doc",
            chunk_id="c1",
            synonyms=["Metformin", "Glucophage"],
        )
        # "also known as" should only list Glucophage
        assert "also known as Glucophage" in answer


# ---------------------------------------------------------------
# Strategy generate() tests
# ---------------------------------------------------------------


class TestKGQAStrategyGenerate:
    @pytest.mark.asyncio
    async def test_basic_generation(self, strategy):
        """Generate a single pair from one concept + one chunk."""
        pairs = await strategy.generate(target_count=1)

        assert len(pairs) == 1
        pair = pairs[0]
        assert isinstance(pair, InstructionTuningPair)
        assert pair.metadata.strategy == "kg"
        assert "Metformin" in pair.instruction
        assert "Harrison's" in pair.response
        assert "chunk-001" in pair.response
        assert pair.metadata.source_concepts == ["C0025598"]
        assert pair.metadata.chunk_ids == ["chunk-001"]
        assert 0.0 <= pair.metadata.confidence_score <= 1.0

    @pytest.mark.asyncio
    async def test_respects_target_count(
        self, mock_neo4j, mock_vector
    ):
        """Stop generating once target_count is reached."""
        concepts = [
            _make_concept(
                name=f"Concept_{i}",
                cui=f"C{i:07d}",
                chunk_ids=[f"chunk-{i}"],
            )
            for i in range(10)
        ]
        mock_neo4j.execute_query = AsyncMock(
            return_value=concepts
        )
        strategy = KGQAStrategy(mock_neo4j, mock_vector)

        pairs = await strategy.generate(target_count=3)
        assert len(pairs) == 3

    @pytest.mark.asyncio
    async def test_short_chunk_filtering(
        self, mock_neo4j, mock_vector
    ):
        """Property 4: chunks < 50 tokens are skipped."""
        short_chunk = _make_chunk(
            content="Too short content here.",
        )
        mock_vector.get_chunk_by_id = AsyncMock(
            return_value=short_chunk,
        )
        strategy = KGQAStrategy(mock_neo4j, mock_vector)

        pairs = await strategy.generate(
            target_count=5, min_chunk_tokens=50
        )
        assert len(pairs) == 0

    @pytest.mark.asyncio
    async def test_long_chunk_not_filtered(
        self, mock_neo4j, mock_vector
    ):
        """Property 4: chunks >= 50 tokens are processed."""
        long_content = " ".join(["word"] * 60)
        long_chunk = _make_chunk(content=long_content)
        mock_vector.get_chunk_by_id = AsyncMock(
            return_value=long_chunk,
        )
        strategy = KGQAStrategy(mock_neo4j, mock_vector)

        pairs = await strategy.generate(
            target_count=1, min_chunk_tokens=50
        )
        assert len(pairs) == 1

    @pytest.mark.asyncio
    async def test_neo4j_failure_returns_empty(
        self, mock_neo4j, mock_vector
    ):
        """Neo4j connection failure → graceful skip."""
        mock_neo4j.execute_query = AsyncMock(
            side_effect=ConnectionError("Neo4j down"),
        )
        strategy = KGQAStrategy(mock_neo4j, mock_vector)

        pairs = await strategy.generate(target_count=5)
        assert pairs == []

    @pytest.mark.asyncio
    async def test_milvus_failure_skips_pair(
        self, mock_neo4j, mock_vector
    ):
        """Milvus failure for a chunk → skip that pair."""
        mock_vector.get_chunk_by_id = AsyncMock(
            side_effect=ConnectionError("Milvus down"),
        )
        strategy = KGQAStrategy(mock_neo4j, mock_vector)

        pairs = await strategy.generate(target_count=5)
        assert pairs == []

    @pytest.mark.asyncio
    async def test_progress_callback(self, strategy):
        """Progress callback is invoked with (generated, target)."""
        calls = []
        callback = lambda gen, tgt: calls.append((gen, tgt))

        await strategy.generate(
            target_count=1, progress_callback=callback
        )
        assert len(calls) == 1
        assert calls[0] == (1, 1)

    @pytest.mark.asyncio
    async def test_empty_concept_name_skipped(
        self, mock_neo4j, mock_vector
    ):
        """Concepts with empty name are skipped."""
        mock_neo4j.execute_query = AsyncMock(
            return_value=[
                _make_concept(name="", cui="C0000000")
            ],
        )
        strategy = KGQAStrategy(mock_neo4j, mock_vector)

        pairs = await strategy.generate(target_count=5)
        assert pairs == []

    @pytest.mark.asyncio
    async def test_chunk_not_found_skipped(
        self, mock_neo4j, mock_vector
    ):
        """Chunk returning None is skipped gracefully."""
        mock_vector.get_chunk_by_id = AsyncMock(
            return_value=None,
        )
        strategy = KGQAStrategy(mock_neo4j, mock_vector)

        pairs = await strategy.generate(target_count=5)
        assert pairs == []


# ---------------------------------------------------------------
# Internal helper tests
# ---------------------------------------------------------------


class TestExtractContent:
    def test_top_level_content(self):
        data = {"content": "Hello world"}
        assert KGQAStrategy._extract_content(data) == "Hello world"

    def test_metadata_content_fallback(self):
        data = {
            "content": "",
            "metadata": {"content": "From metadata"},
        }
        assert (
            KGQAStrategy._extract_content(data) == "From metadata"
        )

    def test_empty_returns_empty(self):
        assert KGQAStrategy._extract_content({}) == ""


class TestExtractDocumentTitle:
    def test_top_level_title(self):
        data = {"document_title": "Harrison's"}
        assert (
            KGQAStrategy._extract_document_title(data)
            == "Harrison's"
        )

    def test_metadata_title_fallback(self):
        data = {"metadata": {"title": "From metadata"}}
        assert (
            KGQAStrategy._extract_document_title(data)
            == "From metadata"
        )

    def test_section_fallback(self):
        data = {"section": "Chapter 5"}
        assert (
            KGQAStrategy._extract_document_title(data)
            == "Chapter 5"
        )

    def test_source_id_fallback(self):
        data = {"source_id": "doc-123"}
        assert (
            KGQAStrategy._extract_document_title(data)
            == "doc-123"
        )

    def test_unknown_source_default(self):
        assert (
            KGQAStrategy._extract_document_title({})
            == "Unknown Source"
        )


class TestParseSynonyms:
    def test_none(self):
        assert KGQAStrategy._parse_synonyms(None) == []

    def test_list(self):
        assert KGQAStrategy._parse_synonyms(
            ["A", "B"]
        ) == ["A", "B"]

    def test_comma_separated_string(self):
        assert KGQAStrategy._parse_synonyms(
            "A, B, C"
        ) == ["A", "B", "C"]

    def test_empty_string(self):
        assert KGQAStrategy._parse_synonyms("") == []

    def test_filters_empty_items(self):
        assert KGQAStrategy._parse_synonyms(
            ["A", "", "B"]
        ) == ["A", "B"]


# ---------------------------------------------------------------
# Unit tests for Task 2.5
# Requirements: 1.1, 1.2, 1.3, 1.4, 1.5, 1.6
# ---------------------------------------------------------------


class TestQuestionTemplateSelectionByConceptType:
    """Verify that specific concept types select the correct question
    templates from TEMPLATES_BY_SEMANTIC_TYPE.

    Requirements: 1.3
    """

    def test_pharmacologic_substance_template_0(self):
        """Pharmacologic Substance index 0 → 'mechanism of action'."""
        q = _generate_question(
            "Metformin",
            "Pharmacologic Substance",
            template_index=0,
        )
        assert "Metformin" in q
        assert "mechanism of action" in q

    def test_pharmacologic_substance_template_1(self):
        """Pharmacologic Substance index 1 → 'indications and contraindications'."""
        q = _generate_question(
            "Aspirin",
            "Pharmacologic Substance",
            template_index=1,
        )
        assert "Aspirin" in q
        assert "indications and contraindications" in q

    def test_pharmacologic_substance_template_2(self):
        """Pharmacologic Substance index 2 → 'adverse effects'."""
        q = _generate_question(
            "Lisinopril",
            "Pharmacologic Substance",
            template_index=2,
        )
        assert "Lisinopril" in q
        assert "adverse effects" in q

    def test_pharmacologic_substance_template_cycles(self):
        """Index beyond list length cycles back to the beginning."""
        q_0 = _generate_question(
            "Warfarin",
            "Pharmacologic Substance",
            template_index=0,
        )
        num_templates = len(
            TEMPLATES_BY_SEMANTIC_TYPE["Pharmacologic Substance"]
        )
        q_wrap = _generate_question(
            "Warfarin",
            "Pharmacologic Substance",
            template_index=num_templates,
        )
        assert q_0 == q_wrap

    def test_disease_or_syndrome_template_0(self):
        """Disease or Syndrome index 0 → 'pathophysiology'."""
        q = _generate_question(
            "Type 2 Diabetes Mellitus",
            "Disease or Syndrome",
            template_index=0,
        )
        assert "Type 2 Diabetes Mellitus" in q
        assert "pathophysiology" in q

    def test_disease_or_syndrome_template_1(self):
        """Disease or Syndrome index 1 → 'clinical presentations'."""
        q = _generate_question(
            "Hypertension",
            "Disease or Syndrome",
            template_index=1,
        )
        assert "Hypertension" in q
        assert "clinical presentations" in q

    def test_disease_or_syndrome_template_2(self):
        """Disease or Syndrome index 2 → 'diagnosed'."""
        q = _generate_question(
            "Asthma",
            "Disease or Syndrome",
            template_index=2,
        )
        assert "Asthma" in q
        assert "diagnosed" in q

    def test_disease_or_syndrome_template_cycles(self):
        """Index beyond list length cycles back."""
        q_0 = _generate_question(
            "COPD",
            "Disease or Syndrome",
            template_index=0,
        )
        num_templates = len(
            TEMPLATES_BY_SEMANTIC_TYPE["Disease or Syndrome"]
        )
        q_wrap = _generate_question(
            "COPD",
            "Disease or Syndrome",
            template_index=num_templates,
        )
        assert q_0 == q_wrap

    def test_therapeutic_procedure_template(self):
        """Therapeutic or Preventive Procedure uses its own templates."""
        q = _generate_question(
            "Coronary Angioplasty",
            "Therapeutic or Preventive Procedure",
            template_index=0,
        )
        assert "Coronary Angioplasty" in q
        assert "indications" in q

    def test_sign_or_symptom_template(self):
        """Sign or Symptom uses its own templates."""
        q = _generate_question(
            "Dyspnea",
            "Sign or Symptom",
            template_index=0,
        )
        assert "Dyspnea" in q
        assert "causes" in q

    def test_unknown_type_uses_default_templates(self):
        """An unrecognized semantic type falls back to DEFAULT_QUESTION_TEMPLATES."""
        q = _generate_question(
            "SomeEntity",
            "Completely Unknown Type",
            template_index=0,
        )
        assert "SomeEntity" in q
        assert "clinical significance" in q

    def test_synonyms_do_not_affect_question(self):
        """Synonyms are accepted but do not change the question text."""
        q_no_syn = _generate_question(
            "Metformin",
            "Pharmacologic Substance",
            synonyms=None,
            template_index=0,
        )
        q_with_syn = _generate_question(
            "Metformin",
            "Pharmacologic Substance",
            synonyms=["Glucophage", "Fortamet"],
            template_index=0,
        )
        assert q_no_syn == q_with_syn


class TestNeo4jQueryConstructionAndResultParsing:
    """Verify Neo4j query execution, parameter passing, and result parsing.

    Requirements: 1.1, 1.2
    """

    @pytest.mark.asyncio
    async def test_fetch_concepts_passes_limit_parameter(self):
        """_fetch_concepts passes the limit parameter to Neo4j."""
        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(return_value=[])
        mock_vector = MagicMock()

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        await strategy._fetch_concepts(limit=100)

        mock_neo4j.execute_query.assert_called_once()
        call_args = mock_neo4j.execute_query.call_args
        # First positional arg is the query, second is the params dict
        assert call_args[0][1] == {"limit": 100}

    @pytest.mark.asyncio
    async def test_fetch_concepts_uses_correct_cypher_query(self):
        """_fetch_concepts uses the _CONCEPT_QUERY Cypher template."""
        from multimodal_librarian.ml.kg_qa_strategy import _CONCEPT_QUERY

        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(return_value=[])
        mock_vector = MagicMock()

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        await strategy._fetch_concepts(limit=50)

        call_args = mock_neo4j.execute_query.call_args
        assert call_args[0][0] == _CONCEPT_QUERY

    @pytest.mark.asyncio
    async def test_fetch_concepts_returns_empty_on_none_result(self):
        """_fetch_concepts returns [] when Neo4j returns None."""
        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(return_value=None)
        mock_vector = MagicMock()

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        result = await strategy._fetch_concepts(limit=10)
        assert result == []

    @pytest.mark.asyncio
    async def test_fetch_concepts_returns_empty_on_exception(self):
        """_fetch_concepts returns [] on any exception (graceful skip)."""
        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(
            side_effect=RuntimeError("Connection refused")
        )
        mock_vector = MagicMock()

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        result = await strategy._fetch_concepts(limit=10)
        assert result == []

    @pytest.mark.asyncio
    async def test_generate_requests_3x_target_count(self):
        """generate() fetches 3× target_count concepts to account for
        filtering."""
        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(return_value=[])
        mock_vector = MagicMock()

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        await strategy.generate(target_count=10)

        call_args = mock_neo4j.execute_query.call_args
        assert call_args[0][1]["limit"] == 30  # 10 * 3

    @pytest.mark.asyncio
    async def test_concept_result_parsing_all_fields(self):
        """Concept results with all fields are parsed correctly into
        InstructionTuningPairs."""
        concept = _make_concept(
            name="Ibuprofen",
            cui="C0020740",
            semantic_type="Pharmacologic Substance",
            synonyms=["Advil", "Motrin"],
            chunk_ids=["chunk-ibu-001"],
        )
        long_content = " ".join(["Ibuprofen is an NSAID used for pain."] * 15)
        chunk = _make_chunk(
            chunk_id="chunk-ibu-001",
            content=long_content,
            document_title="Goodman & Gilman's",
        )

        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(return_value=[concept])
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(return_value=chunk)

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        pairs = await strategy.generate(target_count=1)

        assert len(pairs) == 1
        pair = pairs[0]
        assert "Ibuprofen" in pair.instruction
        assert pair.metadata.strategy == "kg"
        assert pair.metadata.source_concepts == ["C0020740"]
        assert pair.metadata.chunk_ids == ["chunk-ibu-001"]
        assert pair.metadata.source_document == "Goodman & Gilman's"
        assert "Advil" in pair.response
        assert "Motrin" in pair.response

    @pytest.mark.asyncio
    async def test_concept_without_cui_uses_name_in_source_concepts(self):
        """When CUI is empty, source_concepts falls back to concept name."""
        concept = _make_concept(
            name="SomeDisease",
            cui="",
            semantic_type="Disease or Syndrome",
            chunk_ids=["chunk-sd-001"],
        )
        long_content = " ".join(["word"] * 60)
        chunk = _make_chunk(
            chunk_id="chunk-sd-001",
            content=long_content,
        )

        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(return_value=[concept])
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(return_value=chunk)

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        pairs = await strategy.generate(target_count=1)

        assert len(pairs) == 1
        assert pairs[0].metadata.source_concepts == ["SomeDisease"]

    @pytest.mark.asyncio
    async def test_concept_without_semantic_type_is_skipped(self):
        """Concepts with empty semantic_type are skipped."""
        concept = {
            "name": "SomeConcept",
            "cui": "C0000001",
            "semantic_type": "",
            "synonyms": None,
            "chunk_ids": ["chunk-001"],
        }
        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(return_value=[concept])
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(
            return_value=_make_chunk(content=" ".join(["word"] * 60))
        )

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        pairs = await strategy.generate(target_count=5)
        assert pairs == []

    @pytest.mark.asyncio
    async def test_synonyms_parsed_from_comma_string(self):
        """Synonyms stored as comma-separated string in Neo4j are parsed."""
        concept = _make_concept(
            name="Aspirin",
            cui="C0004057",
            semantic_type="Pharmacologic Substance",
            synonyms="Acetylsalicylic Acid, ASA, Bayer",
            chunk_ids=["chunk-asp-001"],
        )
        long_content = " ".join(["Aspirin is an analgesic."] * 15)
        chunk = _make_chunk(
            chunk_id="chunk-asp-001",
            content=long_content,
        )

        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(return_value=[concept])
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(return_value=chunk)

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        pairs = await strategy.generate(target_count=1)

        assert len(pairs) == 1
        assert "Acetylsalicylic Acid" in pairs[0].response


class TestMilvusChunkRetrieval:
    """Verify Milvus chunk retrieval, content extraction, and error handling.

    Requirements: 1.2, 1.4, 1.5
    """

    @pytest.mark.asyncio
    async def test_fetch_chunk_calls_get_chunk_by_id(self):
        """_fetch_chunk delegates to vector_client.get_chunk_by_id."""
        mock_neo4j = MagicMock()
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(
            return_value=_make_chunk(chunk_id="chunk-xyz")
        )

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        result = await strategy._fetch_chunk("chunk-xyz")

        mock_vector.get_chunk_by_id.assert_called_once_with("chunk-xyz")
        assert result is not None
        assert result["chunk_id"] == "chunk-xyz"

    @pytest.mark.asyncio
    async def test_fetch_chunk_returns_none_on_exception(self):
        """_fetch_chunk returns None on any exception (graceful skip)."""
        mock_neo4j = MagicMock()
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(
            side_effect=TimeoutError("Milvus timeout")
        )

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        result = await strategy._fetch_chunk("chunk-001")
        assert result is None

    @pytest.mark.asyncio
    async def test_fetch_chunk_returns_none_when_client_returns_none(self):
        """_fetch_chunk returns None when the vector client returns None."""
        mock_neo4j = MagicMock()
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(return_value=None)

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        result = await strategy._fetch_chunk("nonexistent-chunk")
        assert result is None

    @pytest.mark.asyncio
    async def test_multiple_chunks_per_concept(self):
        """A concept with multiple chunk_ids generates one pair per chunk
        (up to target_count)."""
        concept = _make_concept(
            name="Diabetes",
            cui="C0011849",
            semantic_type="Disease or Syndrome",
            chunk_ids=["chunk-d1", "chunk-d2", "chunk-d3"],
        )
        long_content = " ".join(["word"] * 60)

        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(return_value=[concept])
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(
            return_value=_make_chunk(content=long_content)
        )

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        pairs = await strategy.generate(target_count=3)

        assert len(pairs) == 3
        # Each pair should have a different template (cycling)
        instructions = [p.instruction for p in pairs]
        assert len(set(instructions)) == 3

    @pytest.mark.asyncio
    async def test_milvus_failure_for_one_chunk_continues_others(self):
        """When Milvus fails for one chunk, other chunks still produce
        pairs."""
        concept = _make_concept(
            name="Hypertension",
            cui="C0020538",
            semantic_type="Disease or Syndrome",
            chunk_ids=["chunk-fail", "chunk-ok"],
        )
        long_content = " ".join(["word"] * 60)

        call_count = 0

        async def mock_get_chunk(chunk_id):
            nonlocal call_count
            call_count += 1
            if chunk_id == "chunk-fail":
                raise ConnectionError("Milvus down for this chunk")
            return _make_chunk(
                chunk_id=chunk_id, content=long_content
            )

        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(return_value=[concept])
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(side_effect=mock_get_chunk)

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        pairs = await strategy.generate(target_count=5)

        assert len(pairs) == 1
        assert call_count == 2

    @pytest.mark.asyncio
    async def test_extract_content_prefers_top_level(self):
        """_extract_content prefers top-level 'content' over metadata."""
        chunk = {
            "content": "Top-level content",
            "metadata": {"content": "Metadata content"},
        }
        assert KGQAStrategy._extract_content(chunk) == "Top-level content"

    @pytest.mark.asyncio
    async def test_extract_content_falls_back_to_metadata(self):
        """_extract_content falls back to metadata.content when top-level
        is empty."""
        chunk = {
            "content": "",
            "metadata": {"content": "Metadata content"},
        }
        assert KGQAStrategy._extract_content(chunk) == "Metadata content"

    @pytest.mark.asyncio
    async def test_extract_document_title_fallback_chain(self):
        """_extract_document_title follows the full fallback chain:
        document_title → metadata.title → section → source_id → default."""
        # Each step in the chain
        assert (
            KGQAStrategy._extract_document_title(
                {"document_title": "Harrison's"}
            )
            == "Harrison's"
        )
        assert (
            KGQAStrategy._extract_document_title(
                {"metadata": {"title": "Robbins"}}
            )
            == "Robbins"
        )
        assert (
            KGQAStrategy._extract_document_title(
                {"section": "Chapter 12"}
            )
            == "Chapter 12"
        )
        assert (
            KGQAStrategy._extract_document_title(
                {"source_id": "src-42"}
            )
            == "src-42"
        )
        assert (
            KGQAStrategy._extract_document_title({})
            == "Unknown Source"
        )


class TestComputeConfidence:
    """Verify confidence score computation.

    Requirements: 1.6
    """

    def test_empty_content_returns_zero(self):
        assert KGQAStrategy._compute_confidence("", 50) == 0.0

    def test_content_at_min_tokens_returns_0_5(self):
        content = " ".join(["word"] * 50)
        score = KGQAStrategy._compute_confidence(content, 50)
        assert score == 0.5

    def test_content_well_above_min_returns_higher(self):
        content = " ".join(["word"] * 200)
        score = KGQAStrategy._compute_confidence(content, 50)
        assert score > 0.5

    def test_confidence_clamped_to_1(self):
        content = " ".join(["word"] * 10000)
        score = KGQAStrategy._compute_confidence(content, 50)
        assert score <= 1.0

    def test_confidence_never_negative(self):
        score = KGQAStrategy._compute_confidence("a", 50)
        assert score >= 0.0

    def test_min_tokens_zero_does_not_crash(self):
        """min_tokens=0 should not cause division by zero."""
        content = " ".join(["word"] * 10)
        score = KGQAStrategy._compute_confidence(content, 0)
        assert 0.0 <= score <= 1.0


class TestGenerateEndToEndScenarios:
    """End-to-end generate() scenarios covering multi-concept, template
    cycling, and metadata correctness.

    Requirements: 1.1, 1.2, 1.3, 1.4, 1.5, 1.6
    """

    @pytest.mark.asyncio
    async def test_multiple_concepts_different_types(self):
        """Generate pairs from concepts of different semantic types and
        verify each uses the correct template family."""
        concepts = [
            _make_concept(
                name="Metformin",
                cui="C0025598",
                semantic_type="Pharmacologic Substance",
                chunk_ids=["chunk-met"],
            ),
            _make_concept(
                name="Diabetes",
                cui="C0011849",
                semantic_type="Disease or Syndrome",
                chunk_ids=["chunk-dia"],
            ),
        ]
        long_content = " ".join(["word"] * 60)

        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(return_value=concepts)
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(
            return_value=_make_chunk(content=long_content)
        )

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        pairs = await strategy.generate(target_count=2)

        assert len(pairs) == 2
        # First pair: Pharmacologic Substance template
        assert "Metformin" in pairs[0].instruction
        assert "mechanism of action" in pairs[0].instruction
        # Second pair: Disease or Syndrome template (index 1 cycles)
        assert "Diabetes" in pairs[1].instruction

    @pytest.mark.asyncio
    async def test_template_index_increments_across_concepts(self):
        """Template index increments globally, not per concept."""
        concepts = [
            _make_concept(
                name="Drug_A",
                cui="C0000001",
                semantic_type="Pharmacologic Substance",
                chunk_ids=["chunk-a1", "chunk-a2"],
            ),
        ]
        long_content = " ".join(["word"] * 60)

        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(return_value=concepts)
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(
            return_value=_make_chunk(content=long_content)
        )

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        pairs = await strategy.generate(target_count=2)

        assert len(pairs) == 2
        # Two different templates for the same concept type
        assert pairs[0].instruction != pairs[1].instruction

    @pytest.mark.asyncio
    async def test_pair_metadata_has_correct_structure(self):
        """Every generated pair has valid metadata fields."""
        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(
            return_value=[_make_concept()]
        )
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(
            return_value=_make_chunk()
        )

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        pairs = await strategy.generate(target_count=1)

        assert len(pairs) == 1
        pair = pairs[0]
        assert pair.metadata.strategy == "kg"
        assert isinstance(pair.metadata.source_concepts, list)
        assert len(pair.metadata.source_concepts) > 0
        assert isinstance(pair.metadata.confidence_score, float)
        assert 0.0 <= pair.metadata.confidence_score <= 1.0
        assert pair.metadata.source_document is not None
        assert pair.metadata.chunk_ids is not None
        assert len(pair.metadata.chunk_ids) == 1

    @pytest.mark.asyncio
    async def test_pair_fields_are_non_empty(self):
        """Every generated pair has non-empty instruction, context, and
        response (Property 1 for KG strategy)."""
        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(
            return_value=[_make_concept()]
        )
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(
            return_value=_make_chunk()
        )

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        pairs = await strategy.generate(target_count=1)

        assert len(pairs) == 1
        pair = pairs[0]
        assert len(pair.instruction.strip()) > 0
        assert len(pair.context.strip()) > 0
        assert len(pair.response.strip()) > 0

    @pytest.mark.asyncio
    async def test_context_field_contains_chunk_content(self):
        """The context field of a generated pair contains the chunk
        content."""
        expected_content = " ".join(
            ["Metformin is a biguanide oral antidiabetic."] * 10
        )
        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(
            return_value=[_make_concept()]
        )
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(
            return_value=_make_chunk(content=expected_content)
        )

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        pairs = await strategy.generate(target_count=1)

        assert len(pairs) == 1
        assert pairs[0].context == expected_content

    @pytest.mark.asyncio
    async def test_mixed_short_and_long_chunks(self):
        """Only chunks meeting the token threshold produce pairs."""
        concept = _make_concept(
            name="TestDrug",
            cui="C9999999",
            semantic_type="Pharmacologic Substance",
            chunk_ids=["short-chunk", "long-chunk"],
        )
        short_content = "Too short."
        long_content = " ".join(["word"] * 60)

        async def mock_get_chunk(chunk_id):
            if chunk_id == "short-chunk":
                return _make_chunk(
                    chunk_id="short-chunk", content=short_content
                )
            return _make_chunk(
                chunk_id="long-chunk", content=long_content
            )

        mock_neo4j = MagicMock()
        mock_neo4j.execute_query = AsyncMock(return_value=[concept])
        mock_vector = MagicMock()
        mock_vector.get_chunk_by_id = AsyncMock(side_effect=mock_get_chunk)

        strategy = KGQAStrategy(mock_neo4j, mock_vector)
        pairs = await strategy.generate(target_count=5, min_chunk_tokens=50)

        assert len(pairs) == 1
        assert pairs[0].metadata.chunk_ids == ["long-chunk"]
