#!/bin/bash
"""
Setup Cron-based Cleanup Service

This script sets up cron jobs for automated resource cleanup
on systems that don't use systemd.
"""

set -e

# Configuration
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON_PATH="$(which python3)"
CLEANUP_SCRIPT="${PROJECT_ROOT}/scripts/cleanup-local-resources.py"
SCHEDULED_SCRIPT="${PROJECT_ROOT}/scripts/scheduled-cleanup.py"
LOG_DIR="${PROJECT_ROOT}/logs"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_requirements() {
    print_status "Checking requirements..."
    
    # Check if cron is available
    if ! command -v crontab &> /dev/null; then
        print_error "crontab not found. Please install cron."
        exit 1
    fi
    
    # Check if Python 3 is available
    if ! command -v python3 &> /dev/null; then
        print_error "Python 3 not found. Please install Python 3."
        exit 1
    fi
    
    # Check if cleanup scripts exist
    if [[ ! -f "${CLEANUP_SCRIPT}" ]]; then
        print_error "Cleanup script not found at ${CLEANUP_SCRIPT}"
        exit 1
    fi
    
    if [[ ! -f "${SCHEDULED_SCRIPT}" ]]; then
        print_error "Scheduled cleanup script not found at ${SCHEDULED_SCRIPT}"
        exit 1
    fi
    
    # Ensure log directory exists
    mkdir -p "${LOG_DIR}"
    
    print_success "Requirements check passed"
}

backup_existing_crontab() {
    print_status "Backing up existing crontab..."
    
    if crontab -l &> /dev/null; then
        crontab -l > "${PROJECT_ROOT}/crontab.backup.$(date +%Y%m%d_%H%M%S)"
        print_success "Existing crontab backed up"
    else
        print_status "No existing crontab found"
    fi
}

install_cron_jobs() {
    print_status "Installing cron jobs..."
    
    # Create temporary crontab file
    TEMP_CRONTAB=$(mktemp)
    
    # Get existing crontab if it exists
    if crontab -l &> /dev/null; then
        crontab -l > "${TEMP_CRONTAB}"
    fi
    
    # Add cleanup cron jobs
    cat >> "${TEMP_CRONTAB}" << EOF

# Multimodal Librarian Automated Cleanup Jobs
# Generated by setup-cron-cleanup.sh on $(date)

# Daily cleanup at 2:00 AM - logs, temp files, test artifacts
0 2 * * * cd "${PROJECT_ROOT}" && "${PYTHON_PATH}" "${CLEANUP_SCRIPT}" --files-only --force >> "${LOG_DIR}/daily-cleanup.log" 2>&1

# Weekly cleanup on Sunday at 3:00 AM - Docker images, old backups
0 3 * * 0 cd "${PROJECT_ROOT}" && "${PYTHON_PATH}" "${CLEANUP_SCRIPT}" --containers-only --force >> "${LOG_DIR}/weekly-cleanup.log" 2>&1

# Hourly disk usage check
0 * * * * cd "${PROJECT_ROOT}" && "${PYTHON_PATH}" "${CLEANUP_SCRIPT}" --report-only >> "${LOG_DIR}/disk-usage.log" 2>&1

# Log rotation - keep only last 7 days of cleanup logs
0 4 * * * find "${LOG_DIR}" -name "*cleanup*.log" -mtime +7 -delete

EOF
    
    # Install the new crontab
    crontab "${TEMP_CRONTAB}"
    rm "${TEMP_CRONTAB}"
    
    print_success "Cron jobs installed"
}

create_log_rotation() {
    print_status "Setting up log rotation..."
    
    # Create logrotate configuration if logrotate is available
    if command -v logrotate &> /dev/null; then
        cat > "${PROJECT_ROOT}/cleanup-logrotate.conf" << EOF
${LOG_DIR}/*cleanup*.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 644 ${USER} ${USER}
}
EOF
        print_success "Log rotation configuration created at ${PROJECT_ROOT}/cleanup-logrotate.conf"
        print_status "To enable log rotation, add this to your system logrotate:"
        print_status "sudo cp ${PROJECT_ROOT}/cleanup-logrotate.conf /etc/logrotate.d/multimodal-librarian-cleanup"
    else
        print_warning "logrotate not found. Log rotation will be handled by cron."
    fi
}

verify_installation() {
    print_status "Verifying installation..."
    
    # Check if cron jobs were installed
    if crontab -l | grep -q "Multimodal Librarian Automated Cleanup"; then
        print_success "Cron jobs installed successfully"
    else
        print_error "Cron jobs not found in crontab"
        return 1
    fi
    
    # Test the cleanup script
    print_status "Testing cleanup script..."
    if "${PYTHON_PATH}" "${CLEANUP_SCRIPT}" --dry-run > /dev/null 2>&1; then
        print_success "Cleanup script test passed"
    else
        print_error "Cleanup script test failed"
        return 1
    fi
    
    print_success "Installation verification completed"
}

show_usage_info() {
    print_status "Installation completed successfully!"
    echo ""
    echo "Scheduled Cleanup Jobs:"
    echo "  Daily at 2:00 AM  - Clean up logs, temp files, test artifacts"
    echo "  Weekly on Sunday  - Clean up Docker containers and images"
    echo "  Hourly           - Check disk usage and generate reports"
    echo ""
    echo "Log Files:"
    echo "  Daily cleanup:   ${LOG_DIR}/daily-cleanup.log"
    echo "  Weekly cleanup:  ${LOG_DIR}/weekly-cleanup.log"
    echo "  Disk usage:      ${LOG_DIR}/disk-usage.log"
    echo ""
    echo "Management Commands:"
    echo "  crontab -l                    # View installed cron jobs"
    echo "  crontab -e                    # Edit cron jobs"
    echo "  tail -f ${LOG_DIR}/*cleanup*.log  # Monitor cleanup logs"
    echo ""
    echo "Manual Testing:"
    echo "  ${PYTHON_PATH} ${CLEANUP_SCRIPT} --dry-run"
    echo "  ${PYTHON_PATH} ${CLEANUP_SCRIPT} --files-only"
    echo ""
    echo "Uninstall:"
    echo "  ${PROJECT_ROOT}/scripts/setup-cron-cleanup.sh uninstall"
}

uninstall_cron_jobs() {
    print_status "Uninstalling cron jobs..."
    
    # Create temporary crontab file
    TEMP_CRONTAB=$(mktemp)
    
    # Get existing crontab and remove our jobs
    if crontab -l &> /dev/null; then
        crontab -l | grep -v "Multimodal Librarian Automated Cleanup" | \
                     grep -v "${CLEANUP_SCRIPT}" | \
                     grep -v "${SCHEDULED_SCRIPT}" > "${TEMP_CRONTAB}"
        
        # Install the cleaned crontab
        crontab "${TEMP_CRONTAB}"
        print_success "Cron jobs removed"
    else
        print_status "No crontab found"
    fi
    
    rm "${TEMP_CRONTAB}"
    
    # Remove log rotation config if it exists
    if [[ -f "${PROJECT_ROOT}/cleanup-logrotate.conf" ]]; then
        rm "${PROJECT_ROOT}/cleanup-logrotate.conf"
        print_success "Log rotation configuration removed"
    fi
    
    print_success "Cleanup cron jobs uninstalled"
}

show_status() {
    print_status "Cron-based cleanup status:"
    echo ""
    
    # Show relevant cron jobs
    if crontab -l 2>/dev/null | grep -q "Multimodal Librarian"; then
        echo "Installed cron jobs:"
        crontab -l | grep -A 10 -B 2 "Multimodal Librarian"
    else
        echo "No cleanup cron jobs found"
    fi
    
    echo ""
    echo "Recent log activity:"
    for log_file in "${LOG_DIR}"/*cleanup*.log; do
        if [[ -f "$log_file" ]]; then
            echo "  $(basename "$log_file"): $(wc -l < "$log_file") lines, last modified $(date -r "$log_file")"
        fi
    done
}

main() {
    echo "Multimodal Librarian - Cron-based Cleanup Setup"
    echo "==============================================="
    echo ""
    
    case "${1:-install}" in
        install)
            check_requirements
            backup_existing_crontab
            install_cron_jobs
            create_log_rotation
            verify_installation
            show_usage_info
            ;;
        uninstall)
            uninstall_cron_jobs
            ;;
        status)
            show_status
            ;;
        test)
            "${PYTHON_PATH}" "${CLEANUP_SCRIPT}" --dry-run
            ;;
        logs)
            if [[ -f "${LOG_DIR}/daily-cleanup.log" ]]; then
                tail -f "${LOG_DIR}"/*cleanup*.log
            else
                print_warning "No cleanup logs found yet"
            fi
            ;;
        *)
            echo "Usage: $0 [install|uninstall|status|test|logs]"
            echo ""
            echo "Commands:"
            echo "  install   - Install cron-based cleanup jobs (default)"
            echo "  uninstall - Remove cleanup cron jobs"
            echo "  status    - Show status of cleanup jobs"
            echo "  test      - Test the cleanup script"
            echo "  logs      - Show and follow cleanup logs"
            exit 1
            ;;
    esac
}

main "$@"